application: evote-web
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /favicon.ico
  static_files: images/favicon.ico
- url: /
  script: helloworld.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
